# Generated by Django 2.0.10 on 2019-01-15 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('creation_date', models.DateField(default=datetime.datetime(2019, 1, 15, 19, 38, 49, 757793))),
            ],
        ),
    ]
