# Generated by Django 2.0.10 on 2019-01-15 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 19, 42, 59, 988727)),
        ),
    ]
